### ISSUE TITLE
JSON not updating.

### ISSUE THREAD

**Issue by marcwhitbread** [colynb/gulp-data#17]
I'm having an issue with a task I'm watching. I'm compiling handlebars templates, partials, and dynamically loading a JSON file for each hbs template.

The task compiles 100% fine manually kicking it off but when I use watch, the JSON data is not updated. I am watching all templates, partials and JSON files. The task is firing successfully when any of the files are modified. It just doesn't pick up any changes to the JSON files.

Here's what I'm doing:
```js
return gulp.src(template_src)
	.pipe(data(function(file) {
		var dir = (file.path.split('/templates/')[1].split('/').length > 1) ? file.path.split('/templates/')[1].split('/')[0] : '';
		return require(data_src + '/' + dir + '/' + path.basename(file.path, '.hbs') + '.json');
    }))
    .pipe(handlebars(null, hbs_options))
    .pipe(rename(function(path) {
    	path.extname = '.html';
    }))
    .pipe(minify_html(min_options))
    .pipe(gulp.dest(dest));
```

**Comment by Shinchy** [comment]
This is down to the default node.js require function caching data.

What I did was use this function:

    // De-caching for Data files
    function requireUncached( $module ) {
        delete require.cache[require.resolve( $module )];
        return require( $module );
   }

Then I simply call 'requireUncached instead. e.g.

     .pipe( data(function(file){
	     return requireUncached('./app/data/myJsonFile.json');
     }))

**Comment by marcwhitbread** [comment]
Perfect! I figured it was caching. Thanks a ton. :+1:
